<a href="https://colab.research.google.com/github/vragarwal/FDS-Results/blob/main/vradhi%20exp%203%20fds.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import pandas as pd
import numpy as np

In [99]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv("V_S_DATA SET_CLIMATE.csv")

Saving V_S_DATA SET_CLIMATE.csv to V_S_DATA SET_CLIMATE (2).csv

In [100]:
data.head()

,country,longitude,timezone,last_updated,temperature_celsius,condition_text,wind_kph,wind_degree,wind_direction,precip_mm,humidity,visibility_km,gust_mph,air_quality_Ozone,air_quality_us-epa-index,sunset,moonrise,moon_phase
0,Afghanistan,69.18,Asia/Kabul,16-05-2024 13:15,26.6,Partly Cloudy,13.3,338,NNW,0.0,24,10.0,9.5,103.0,1,6:50 PM,12:12 PM,Waxing Gibbous
1,Albania,19.82,Europe/Tirane,16-05-2024 10:45,19.0,Partly cloudy,11.2,320,NW,0.1,94,10.0,11.4,97.3,1,7:54 PM,12:58 PM,Waxing Gibbous
2,Algeria,3.05,Africa/Algiers,16-05-2024 09:45,23.0,Sunny,15.1,280,W,0.0,29,10.0,13.9,12.2,1,7:50 PM,1:15 PM,Waxing Gibbous
3,Andorra,1.52,Europe/Andorra,16-05-2024 10:45,6.3,Light drizzle,11.9,215,SW,0.3,61,2.0,8.5,64.4,1,9:11 PM,2:12 PM,Waxing Gibbous
4,Angola,13.23,Africa/Luanda,16-05-2024 09:45,26.0,Partly cloudy,13.0,150,SSE,0.0,89,10.0,12.5,19.0,5,5:55 PM,1:17 PM,Waxing Gibbous

In [101]:
data.describe()

,longitude,temperature_celsius,wind_kph,wind_degree,precip_mm,humidity,visibility_km,gust_mph,air_quality_Ozone,air_quality_us-epa-index
count,155336.000000,155336.000000,155336.000000,155336.000000,155336.000000,155336.000000,155336.000000,155336.000000,155336.000000,155336.000000
mean,21.871921,21.382798,12.763744,169.713724,0.131491,67.005401,9.517604,11.228890,57.761376,1.664817
std,65.775991,9.464173,11.220862,103.518100,0.556538,23.609551,2.690283,8.376131,30.759617,0.923014
min,-175.200000,-29.800000,3.600000,1.000000,0.000000,2.000000,0.000000,2.200000,0.000000,1.000000
25%,-6.836100,16.100000,6.100000,81.000000,0.000000,52.000000,10.000000,6.200000,38.000000,1.000000
50%,21.433300,23.700000,10.800000,163.000000,0.000000,73.000000,10.000000,9.400000,54.400000,1.000000
75%,49.882200,27.900000,17.300000,257.000000,0.020000,86.000000,10.000000,14.900000,73.000000,2.000000
max,179.220000,79.300000,2963.200000,360.000000,42.240000,100.000000,32.000000,1845.700000,480.700000,6.000000

In [102]:
temperature = data["temperature_celsius"]

activity 1:

In [103]:
frequency = temperature.value_counts()

print(frequency)

temperature_celsius
 26.3    2007
 25.3    1997
 25.1    1989
 26.2    1985
 25.2    1949
         ...
 48.2       1
-20.3       1
 79.3       1
-25.0       1
-10.1       1
Name: count, Length: 708, dtype: int64

In [104]:
mean = np.mean(temperature)

print("Mean = ", mean)

Mean =  21.3827979347994

In [105]:
median = np.median(temperature)

print("Median =", median)

Median = 23.7

In [106]:
mode = temperature.mode()[0]

print("Mode =", mode)

Mode = 26.3

In [107]:
variance = np.var(temperature)

print("Variance =", variance)

Variance = 89.56999925555004

In [108]:
standard_deviation = np.std(temperature)

print("Standard Deviation =", standard_deviation)

Standard Deviation = 9.464142816734649

In [109]:
Q1 = np.percentile(temperature, 25)
Q3 = np.percentile(temperature, 75)

IQR = Q3 - Q1

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

Q1 = 16.1
Q3 = 27.9
IQR = 11.799999999999997

activity 2:

In [110]:
n = len(temperature)

In [111]:
total = 0

for value in temperature:
    total = total + value

mean = total / n
print("Mean = ", mean)

Mean =  21.382797934804692

In [112]:
values = list(temperature)
values.sort()

if n % 2 == 1:
    median = values[n // 2]
else:
    median = (values[n // 2 - 1] + values[n // 2]) / 2

print("Median =", median)

Median = 23.7

In [113]:
frequency = {}

for value in temperature:
    if value in frequency:
        frequency[value] = frequency[value] + 1
    else:
        frequency[value] = 1

highest_frequency = 0
mode = None

for value in frequency:
    if frequency[value] > highest_frequency:
        highest_frequency = frequency[value]
        mode = value

print("Mode =", mode)
print("Frequency =", highest_frequency)

Mode = 26.3
Frequency = 2007

In [114]:
total = 0

for value in temperature:
    total = total + (value - mean) ** 2

variance = total / n
print("Variance =", variance)

Variance = 89.56999925555004

In [115]:
standard_deviation = variance ** 0.5
print("Standard Deviation =", standard_deviation)

Standard Deviation = 9.464142816734649

In [116]:
Q1_position = (n + 1) / 4
Q3_position = 3 * (n + 1) / 4

print("Q1 position =", Q1_position)
print("Q3 position =", Q3_position)

Q1 position = 38834.25
Q3 position = 116502.75

python indexing starts from 0 therefore subtract 1 to make index

In [117]:
Q1_index = int(Q1_position) - 1
Q3_index = int(Q3_position) - 1

Q1 = values[Q1_index]
Q3 = values[Q3_index]

IQR = Q3 - Q1

print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

Q1 = 16.1
Q3 = 27.9
IQR = 11.799999999999997

In [118]:
print("Mean =", mean)
print("Median =", median)
print("Mode =", mode)
print("Standard Deviation =", standard_deviation)
print("Variance =", variance)
print("IQR =", IQR)

Mean = 21.382797934804692
Median = 23.7
Mode = 26.3
Standard Deviation = 9.464142816734649
Variance = 89.56999925555004
IQR = 11.799999999999997

activity 3:

In [119]:
bins = [-30, -20, -10, 0, 10, 20, 30, 40, 50, 60, 70, 80]

groups = pd.cut(temperature, bins=bins)

print(groups.head())

0    (20, 30]
1    (10, 20]
2    (20, 30]
3     (0, 10]
4    (20, 30]
Name: temperature_celsius, dtype: category
Categories (11, interval[int64, right]): [(-30, -20] < (-20, -10] < (-10, 0] < (0, 10] ... (40, 50] <
                                          (50, 60] < (60, 70] < (70, 80]]

In [120]:
frequency = {}

for group in groups:
    if group in frequency:
        frequency[group] = frequency[group] + 1
    else:
        frequency[group] = 1

frequency = dict(sorted(frequency.items(), key=lambda x: x[0].left))

for group in frequency:
    print(group, "=", frequency[group])

(-30, -20] = 103
(-20, -10] = 544
(-10, 0] = 3148
(0, 10] = 16957
(10, 20] = 34041
(20, 30] = 78615
(30, 40] = 20638
(40, 50] = 1289
(70, 80] = 1

In [121]:
midpoints = {}

for group in frequency:
    lower = group.left
    upper = group.right

    midpoint = (lower + upper) / 2

    midpoints[group] = midpoint

    print(group, "Midpoint =", midpoint)

(-30, -20] Midpoint = -25.0
(-20, -10] Midpoint = -15.0
(-10, 0] Midpoint = -5.0
(0, 10] Midpoint = 5.0
(10, 20] Midpoint = 15.0
(20, 30] Midpoint = 25.0
(30, 40] Midpoint = 35.0
(40, 50] Midpoint = 45.0
(70, 80] Midpoint = 75.0

In [122]:
total_fx = 0
total_f = 0

for group in frequency:
    f = frequency[group]
    x = midpoints[group]

    total_fx = total_fx + (f * x)
    total_f = total_f + f

mean = total_fx / total_f

print("Grouped Mean =", mean)

Grouped Mean = 21.338968429726528

In [123]:
highest_frequency = 0
mode_group = None

for group in frequency:
    if frequency[group] > highest_frequency:
        highest_frequency = frequency[group]
        mode_group = group

print("Modal Group =", mode_group)
print("Frequency =", highest_frequency)

Modal Group = (20, 30]
Frequency = 78615

In [124]:
cumulative_frequency = 0

for group in frequency:
    cumulative_frequency = cumulative_frequency + frequency[group]

    print(group, "Frequency =", frequency[group],
          "Cumulative Frequency =", cumulative_frequency)

(-30, -20] Frequency = 103 Cumulative Frequency = 103
(-20, -10] Frequency = 544 Cumulative Frequency = 647
(-10, 0] Frequency = 3148 Cumulative Frequency = 3795
(0, 10] Frequency = 16957 Cumulative Frequency = 20752
(10, 20] Frequency = 34041 Cumulative Frequency = 54793
(20, 30] Frequency = 78615 Cumulative Frequency = 133408
(30, 40] Frequency = 20638 Cumulative Frequency = 154046
(40, 50] Frequency = 1289 Cumulative Frequency = 155335
(70, 80] Frequency = 1 Cumulative Frequency = 155336

In [125]:
N = total_f

median_position = N / 2

cumulative_frequency = 0

for group in frequency:
    cumulative_frequency = cumulative_frequency + frequency[group]

    if cumulative_frequency >= median_position:
        median_group = group
        break

print("Median Position =", median_position)
print("Median Group =", median_group)

Median Position = 77668.0
Median Group = (20, 30]

In [126]:
L = median_group.left
h = median_group.right - median_group.left
f = frequency[median_group]

CF = 0

for group in frequency:
    if group == median_group:
        break

    CF = CF + frequency[group]

median = L + ((median_position - CF) / f) * h

print("Grouped Median =", median)

Grouped Median = 22.909750047700822

In [127]:
Q1_position = N / 4

cumulative_frequency = 0

for group in frequency:
    cumulative_frequency = cumulative_frequency + frequency[group]

    if cumulative_frequency >= Q1_position:
        Q1_group = group
        break

print("Q1 Position =", Q1_position)
print("Q1 Group =", Q1_group)

Q1 Position = 38834.0
Q1 Group = (10, 20]

In [128]:
L = Q1_group.left
h = Q1_group.right - Q1_group.left
f = frequency[Q1_group]

CF = 0

for group in frequency:
    if group == Q1_group:
        break

    CF = CF + frequency[group]

Q1 = L + ((Q1_position - CF) / f) * h

print("Q1 =", Q1)

Q1 = 15.311829852237008

In [129]:
Q3_position = 3 * N / 4

cumulative_frequency = 0

for group in frequency:
    cumulative_frequency = cumulative_frequency + frequency[group]

    if cumulative_frequency >= Q3_position:
        Q3_group = group
        break

print("Q3 Position =", Q3_position)
print("Q3 Group =", Q3_group)

Q3 Position = 116502.0
Q3 Group = (20, 30]

In [130]:
L = Q3_group.left
h = Q3_group.right - Q3_group.left
f = frequency[Q3_group]

CF = 0

for group in frequency:
    if group == Q3_group:
        break

    CF = CF + frequency[group]

Q3 = L + ((Q3_position - CF) / f) * h

print("Q3 =", Q3)

Q3 = 27.849519811740763

In [131]:
IQR = Q3 - Q1

print("IQR =", IQR)

IQR = 12.537689959503755

In [132]:
total = 0

for group in frequency:
    f = frequency[group]
    x = midpoints[group]

    total = total + f * (x - mean) ** 2

variance = total / total_f

print("Grouped Variance =", variance)

Grouped Variance = 94.29821777502433

In [133]:
standard_deviation = variance ** 0.5

print("Grouped Standard Deviation =", standard_deviation)

Grouped Standard Deviation = 9.710726943696045

In [134]:
print("Frequency =", frequency)
print("Mean =", mean)
print("Mode Group =", mode_group)
print("Median =", median)
print("Variance =", variance)
print("Standard Deviation =", standard_deviation)
print("Q1 =", Q1)
print("Q3 =", Q3)
print("IQR =", IQR)

Frequency = {Interval(-30, -20, closed='right'): 103, Interval(-20, -10, closed='right'): 544, Interval(-10, 0, closed='right'): 3148, Interval(0, 10, closed='right'): 16957, Interval(10, 20, closed='right'): 34041, Interval(20, 30, closed='right'): 78615, Interval(30, 40, closed='right'): 20638, Interval(40, 50, closed='right'): 1289, Interval(70, 80, closed='right'): 1}
Mean = 21.338968429726528
Mode Group = (20, 30]
Median = 22.909750047700822
Variance = 94.29821777502433
Standard Deviation = 9.710726943696045
Q1 = 15.311829852237008
Q3 = 27.849519811740763
IQR = 12.537689959503755